apiVersion: v1
kind: ConfigMap
metadata:
  name: blueedge-config
  namespace: blueedge
data:
  ADMIN_USERNAME: "admin"
  JWT_EXPIRES_IN: "30d"
  BFF_BASE_URL: "http://blueedge-bff:8080/api/v1"
  K8S_API_SERVER: "https://kubernetes.default.svc"
  K8S_SKIP_TLS_VERIFY: "true"
  KUBEEDGE_TOKEN_SECRET_NAMESPACE: "kubeedge"
  KUBEEDGE_TOKEN_SECRET_NAME: "tokensecret"
  KUBEEDGE_TOKEN_SECRET_KEY: "tokendata"
  KUBEEDGE_TOKEN_MIN_VALIDITY_SECONDS: "300"
