apiVersion: apps/v1
kind: Deployment
metadata:
  name: blueedge-frontend
  namespace: blueedge
  labels:
    app: blueedge-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blueedge-frontend
  template:
    metadata:
      labels:
        app: blueedge-frontend
    spec:
      imagePullSecrets:
        - name: acr-pull-secret
      nodeSelector:
        kubernetes.io/hostname: k8s-master
      containers:
        - name: blueedge-frontend
          image: crpi-wte052aohcsqbtge.cn-hangzhou.personal.cr.aliyuncs.com/xk-private/blueedge:frontend-amd64-2026061003
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: blueedge-frontend
  namespace: blueedge
  labels:
    app: blueedge-frontend
spec:
  type: NodePort
  selector:
    app: blueedge-frontend
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30080
