import { Plus, Trash2 } from "lucide-react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import type { ContainerForm, ContainerPortForm, EnvFromForm, EnvItemForm, LifecycleActionForm, ProbeForm, VolumeMountForm } from "./container-model";
import { formId } from "./container-model";

interface Props {
  value: ContainerForm;
  onChange: (value: ContainerForm) => void;
  onRemove?: () => void;
  title: string;
  isInit?: boolean;
  nameId?: string;
  imageId?: string;
  nameError?: string;
  imageError?: string;
}

function OptionalBadge() {
  return <span className="ml-2 rounded border border-[var(--color-border)] bg-[var(--color-bg-soft)] px-1.5 py-0.5 text-[10px] font-normal leading-none text-[var(--color-text-tertiary)]">选填</span>;
}

function StringList({ label, values, onChange, placeholder }: { label: string; values: string[]; onChange: (values: string[]) => void; placeholder: string }) {
  return <div className="space-y-2">
    <div className="flex items-center justify-between"><Label className="text-xs text-[var(--color-text-secondary)]">{label}</Label><Button type="button" variant="ghost" size="sm" className="h-7 text-xs" onClick={() => onChange([...values, ""])}><Plus className="mr-1 h-3 w-3" />添加</Button></div>
    {values.map((item, index) => <div key={index} className="flex gap-2"><Input className="h-8 text-xs font-mono" value={item} placeholder={placeholder} onChange={(event) => onChange(values.map((value, i) => i === index ? event.target.value : value))}/><Button type="button" variant="ghost" size="icon" className="h-8 w-8" onClick={() => onChange(values.filter((_, i) => i !== index))}><Trash2 className="h-3.5 w-3" /></Button></div>)}
  </div>;
}

function ProbeEditor({ label, value, onChange }: { label: string; value: ProbeForm; onChange: (value: ProbeForm) => void }) {
  return <div className="rounded-lg border border-[var(--color-border)] p-3 space-y-3">
    <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={value.enabled} onChange={(e) => onChange({ ...value, enabled: e.target.checked })} className="h-4 w-4 accent-[var(--color-brand)]" />{label}</label>
    {value.enabled && <>
      <div className="grid grid-cols-2 gap-3"><Select value={value.type} onValueChange={(type: ProbeForm["type"]) => onChange({ ...value, type })}><SelectTrigger className="h-8 text-xs"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="httpGet">HTTP 请求</SelectItem><SelectItem value="tcpSocket">TCP 端口</SelectItem><SelectItem value="exec">执行命令</SelectItem></SelectContent></Select>{value.type !== "exec" && <Input className="h-8 text-xs" value={value.port} placeholder="端口" onChange={(e) => onChange({ ...value, port: e.target.value })}/>}</div>
      {value.type === "httpGet" && <div className="grid grid-cols-[120px_1fr_1fr] gap-2"><Select value={value.scheme} onValueChange={(scheme: ProbeForm["scheme"]) => onChange({ ...value, scheme })}><SelectTrigger className="h-8 text-xs"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="HTTP">HTTP</SelectItem><SelectItem value="HTTPS">HTTPS</SelectItem></SelectContent></Select><Input className="h-8 text-xs" value={value.host} placeholder="请求主机（可选）" onChange={(e) => onChange({ ...value, host: e.target.value })}/><Input className="h-8 text-xs" value={value.path} placeholder="URL 路径，如 /health" onChange={(e) => onChange({ ...value, path: e.target.value })}/></div>} 
      {value.type === "exec" && <StringList label="检查命令" values={value.command} onChange={(command) => onChange({ ...value, command })} placeholder="命令参数"/>}
      <div className="grid grid-cols-4 gap-2">{(["initialDelaySeconds", "periodSeconds", "timeoutSeconds", "failureThreshold"] as const).map((key) => <Input key={key} className="h-8 text-xs" value={value[key]} placeholder={key} onChange={(e) => onChange({ ...value, [key]: e.target.value })}/>)}</div>
    </>}
  </div>;
}

function LifecycleEditor({ label, value, onChange }: { label: string; value: LifecycleActionForm; onChange: (value: LifecycleActionForm) => void }) {
  return <div className="rounded-lg border border-[var(--color-border)] p-3 space-y-3"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={value.enabled} onChange={(e) => onChange({ ...value, enabled: e.target.checked })} className="h-4 w-4 accent-[var(--color-brand)]"/>{label}</label>{value.enabled && <><Select value={value.type} onValueChange={(type: LifecycleActionForm["type"]) => onChange({ ...value, type })}><SelectTrigger className="h-8 text-xs"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="exec">命令行脚本</SelectItem><SelectItem value="httpGet">HTTP 请求</SelectItem></SelectContent></Select>{value.type === "exec" ? <StringList label="运行命令" values={value.command} onChange={(command) => onChange({ ...value, command })} placeholder="每项对应一个命令参数"/> : <div className="grid grid-cols-2 gap-2"><Select value={value.scheme} onValueChange={(scheme: LifecycleActionForm["scheme"]) => onChange({ ...value, scheme })}><SelectTrigger className="h-8 text-xs"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="HTTP">HTTP</SelectItem><SelectItem value="HTTPS">HTTPS</SelectItem></SelectContent></Select><Input className="h-8 text-xs" value={value.port} placeholder="端口" onChange={(e) => onChange({ ...value, port: e.target.value })}/><Input className="h-8 text-xs" value={value.host} placeholder="主机（可选）" onChange={(e) => onChange({ ...value, host: e.target.value })}/><Input className="h-8 text-xs" value={value.path} placeholder="路径，如 /shutdown" onChange={(e) => onChange({ ...value, path: e.target.value })}/></div>}</>}</div>;
}

export function ContainerEditor({ value, onChange, onRemove, title, isInit = false, nameId, imageId, nameError, imageError }: Props) {
  const addEnv = () => onChange({ ...value, env: [...value.env, { id: formId("env"), name: "", source: "value", value: "", resourceName: "", key: "" }] });
  const addEnvFrom = () => onChange({ ...value, envFrom: [...value.envFrom, { id: formId("envfrom"), source: "configMapRef", name: "", prefix: "" }] });
  const addMount = () => onChange({ ...value, volumeMounts: [...value.volumeMounts, { id: formId("mount"), name: "", mountPath: "", subPath: "", subPathExpr: "", readOnly: false }] });
  const addPort = () => onChange({ ...value, ports: [...value.ports, { id: formId("port"), name: "", containerPort: "", hostPort: "", hostIP: "", protocol: "TCP" }] });
  const patchEnv = (id: string, patch: Partial<EnvItemForm>) => onChange({ ...value, env: value.env.map((item) => item.id === id ? { ...item, ...patch } : item) });
  const patchEnvFrom = (id: string, patch: Partial<EnvFromForm>) => onChange({ ...value, envFrom: value.envFrom.map((item) => item.id === id ? { ...item, ...patch } : item) });
  const patchMount = (id: string, patch: Partial<VolumeMountForm>) => onChange({ ...value, volumeMounts: value.volumeMounts.map((item) => item.id === id ? { ...item, ...patch } : item) });
  const patchPort = (id: string, patch: Partial<ContainerPortForm>) => onChange({ ...value, ports: value.ports.map((item) => item.id === id ? { ...item, ...patch } : item) });

  return <div className="rounded-lg border border-[var(--color-border)] bg-white p-4 space-y-4">
    <div className="flex items-center justify-between"><div className="font-medium text-sm text-[var(--color-text-primary)]">{title}</div>{onRemove && <Button type="button" variant="ghost" size="sm" className="text-[var(--color-text-secondary)]" onClick={onRemove}><Trash2 className="mr-1 h-3.5 w-3.5"/>删除容器</Button>}</div>
    <div className="grid grid-cols-2 gap-3"><div><Label className="text-xs">容器名称 *</Label><Input id={nameId} aria-invalid={Boolean(nameError)} className="mt-1 h-9 text-sm" value={value.name} onChange={(e) => onChange({ ...value, name: e.target.value })}/>{nameError && <p className="mt-1 text-xs text-[var(--color-danger)]">{nameError}</p>}</div><div><Label className="text-xs">容器镜像 *</Label><Input id={imageId} aria-invalid={Boolean(imageError)} className="mt-1 h-9 text-sm" value={value.image} onChange={(e) => onChange({ ...value, image: e.target.value })}/>{imageError && <p className="mt-1 text-xs text-[var(--color-danger)]">{imageError}</p>}</div></div>
    <div className="grid grid-cols-2 gap-3"><div><Label className="text-xs">镜像拉取策略</Label><Select value={value.imagePullPolicy} onValueChange={(imagePullPolicy: ContainerForm["imagePullPolicy"]) => onChange({ ...value, imagePullPolicy })}><SelectTrigger className="mt-1 h-9 text-sm"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="IfNotPresent">IfNotPresent</SelectItem><SelectItem value="Always">Always</SelectItem><SelectItem value="Never">Never</SelectItem></SelectContent></Select></div><label className="mt-6 flex items-center gap-2 text-sm"><input type="checkbox" checked={value.privileged} onChange={(e) => onChange({ ...value, privileged: e.target.checked })} className="h-4 w-4 accent-[var(--color-brand)]"/>特权容器</label></div>
    <Accordion type="multiple" className="w-full">
      <AccordionItem value="resources"><AccordionTrigger className="text-sm"><span>资源配额<OptionalBadge /></span></AccordionTrigger><AccordionContent className="space-y-4"><div className="grid grid-cols-2 gap-3">{([['cpuRequest','CPU 请求量'],['cpuLimit','CPU 限制量'],['memoryRequest','内存请求量'],['memoryLimit','内存限制量']] as const).map(([key,label]) => <div key={key}><Label className="text-xs">{label}</Label><Input className="mt-1 h-8 text-xs" value={value[key]} onChange={(e) => onChange({ ...value, [key]: e.target.value })}/></div>)}</div><div className="rounded-lg border border-[var(--color-border)] bg-[var(--color-bg-soft)] p-3"><div className="mb-3 text-xs font-medium text-[var(--color-text-secondary)]">GPU 扩展资源 <OptionalBadge /></div><div className="grid grid-cols-2 gap-3"><div><Label className="text-xs">设备资源名称</Label><Input className="mt-1 h-8 bg-white text-xs" value={value.gpuResourceName} placeholder="如 nvidia.com/gpu" onChange={(e)=>onChange({...value,gpuResourceName:e.target.value})}/></div><div><Label className="text-xs">数量</Label><Input type="number" min={1} className="mt-1 h-8 bg-white text-xs" value={value.gpuCount} placeholder="如 1" onChange={(e)=>onChange({...value,gpuCount:e.target.value})}/></div></div><p className="mt-2 text-xs text-[var(--color-text-tertiary)]">资源名称必须与集群设备插件上报的扩展资源一致，例如 nvidia.com/gpu。</p></div></AccordionContent></AccordionItem>
      <AccordionItem value="ports"><AccordionTrigger className="text-sm"><span>网络端口<OptionalBadge /></span></AccordionTrigger><AccordionContent className="space-y-3"><div className="flex justify-end"><Button type="button" variant="outline" size="sm" onClick={addPort}><Plus className="mr-1 h-3.5 w-3.5"/>添加端口</Button></div>{value.ports.map((port) => <div key={port.id} className="grid grid-cols-[1fr_1fr_1fr_1fr_120px_32px] gap-2"><Input className="h-8 text-xs" value={port.name} placeholder="名称" onChange={(e) => patchPort(port.id, { name: e.target.value })}/><Input className="h-8 text-xs" value={port.containerPort} placeholder="容器端口" onChange={(e) => patchPort(port.id, { containerPort: e.target.value })}/><Input className="h-8 text-xs" value={port.hostPort} placeholder="主机端口（可选）" onChange={(e) => patchPort(port.id, { hostPort: e.target.value })}/><Input className="h-8 text-xs" value={port.hostIP} placeholder="Host IP（可选）" onChange={(e) => patchPort(port.id, { hostIP: e.target.value })}/><Select value={port.protocol} onValueChange={(protocol: ContainerPortForm["protocol"]) => patchPort(port.id, { protocol })}><SelectTrigger className="h-8 text-xs"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="TCP">TCP</SelectItem><SelectItem value="UDP">UDP</SelectItem><SelectItem value="SCTP">SCTP</SelectItem></SelectContent></Select><Button type="button" variant="ghost" size="icon" className="h-8 w-8" onClick={() => onChange({ ...value, ports: value.ports.filter((item) => item.id !== port.id) })}><Trash2 className="h-3.5 w-3.5"/></Button></div>)}</AccordionContent></AccordionItem>
      <AccordionItem value="command"><AccordionTrigger className="text-sm"><span>启动命令<OptionalBadge /></span></AccordionTrigger><AccordionContent className="grid grid-cols-2 gap-4"><StringList label="Command" values={value.command} onChange={(command) => onChange({ ...value, command })} placeholder="如 /bin/sh"/><StringList label="Args" values={value.args} onChange={(args) => onChange({ ...value, args })} placeholder="每项对应一个参数"/></AccordionContent></AccordionItem>
      <AccordionItem value="env"><AccordionTrigger className="text-sm"><span>环境变量<OptionalBadge /></span></AccordionTrigger><AccordionContent className="space-y-4"><div className="flex justify-end"><Button type="button" variant="outline" size="sm" onClick={addEnv}><Plus className="mr-1 h-3.5 w-3.5"/>逐项添加</Button></div>{value.env.map((item) => <div key={item.id} className="grid grid-cols-[150px_1fr_1fr_32px] gap-2"><Select value={item.source} onValueChange={(source: EnvItemForm["source"]) => patchEnv(item.id,{source})}><SelectTrigger className="h-8 text-xs"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="value">键值对</SelectItem><SelectItem value="configMapKeyRef">ConfigMap 键</SelectItem><SelectItem value="secretKeyRef">Secret 键</SelectItem></SelectContent></Select><Input className="h-8 text-xs" value={item.name} placeholder="变量名" onChange={(e)=>patchEnv(item.id,{name:e.target.value})}/>{item.source === "value" ? <Input className="h-8 text-xs" value={item.value} placeholder="值" onChange={(e)=>patchEnv(item.id,{value:e.target.value})}/> : <div className="grid grid-cols-2 gap-2"><Input className="h-8 text-xs" value={item.resourceName} placeholder="资源名称" onChange={(e)=>patchEnv(item.id,{resourceName:e.target.value})}/><Input className="h-8 text-xs" value={item.key} placeholder="键" onChange={(e)=>patchEnv(item.id,{key:e.target.value})}/></div>}<Button type="button" variant="ghost" size="icon" className="h-8 w-8" onClick={()=>onChange({...value,env:value.env.filter(v=>v.id!==item.id)})}><Trash2 className="h-3.5 w-3.5"/></Button></div>)}<div className="flex justify-end"><Button type="button" variant="outline" size="sm" onClick={addEnvFrom}><Plus className="mr-1 h-3.5 w-3.5"/>整体导入 ConfigMap/Secret</Button></div>{value.envFrom.map((item)=><div key={item.id} className="grid grid-cols-[170px_1fr_1fr_32px] gap-2"><Select value={item.source} onValueChange={(source:EnvFromForm["source"])=>patchEnvFrom(item.id,{source})}><SelectTrigger className="h-8 text-xs"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="configMapRef">ConfigMap</SelectItem><SelectItem value="secretRef">Secret</SelectItem></SelectContent></Select><Input className="h-8 text-xs" value={item.name} placeholder="资源名称" onChange={(e)=>patchEnvFrom(item.id,{name:e.target.value})}/><Input className="h-8 text-xs" value={item.prefix} placeholder="变量前缀（可选）" onChange={(e)=>patchEnvFrom(item.id,{prefix:e.target.value})}/><Button type="button" variant="ghost" size="icon" className="h-8 w-8" onClick={()=>onChange({...value,envFrom:value.envFrom.filter(v=>v.id!==item.id)})}><Trash2 className="h-3.5 w-3.5"/></Button></div>)}</AccordionContent></AccordionItem>
      <AccordionItem value="mounts"><AccordionTrigger className="text-sm"><span>数据卷挂载<OptionalBadge /></span></AccordionTrigger><AccordionContent className="space-y-3"><div className="flex justify-end"><Button type="button" variant="outline" size="sm" onClick={addMount}><Plus className="mr-1 h-3.5 w-3.5"/>添加挂载</Button></div>{value.volumeMounts.map((item)=><div key={item.id} className="grid grid-cols-2 gap-2 rounded-lg border border-[var(--color-border)] bg-[var(--color-bg-soft)] p-3"><Input className="h-8 bg-white text-xs" value={item.name} placeholder="Volume 名称" onChange={(e)=>patchMount(item.id,{name:e.target.value})}/><Input className="h-8 bg-white text-xs" value={item.mountPath} placeholder="容器路径 mountPath" onChange={(e)=>patchMount(item.id,{mountPath:e.target.value})}/><Input className="h-8 bg-white text-xs" value={item.subPath} placeholder="subPath（可选）" onChange={(e)=>patchMount(item.id,{subPath:e.target.value,subPathExpr:""})}/><Input className="h-8 bg-white text-xs" value={item.subPathExpr} placeholder="subPathExpr（可选）" onChange={(e)=>patchMount(item.id,{subPathExpr:e.target.value,subPath:""})}/><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={item.readOnly} onChange={(e)=>patchMount(item.id,{readOnly:e.target.checked})} className="h-4 w-4 accent-[var(--color-brand)]"/>只读</label><button type="button" className="action-button is-danger justify-self-end" title="删除挂载" aria-label="删除挂载" onClick={()=>onChange({...value,volumeMounts:value.volumeMounts.filter(v=>v.id!==item.id)})}><Trash2 className="h-3.5 w-3.5"/></button></div>)}</AccordionContent></AccordionItem>
      {!isInit && <AccordionItem value="health"><AccordionTrigger className="text-sm"><span>健康检查<OptionalBadge /></span></AccordionTrigger><AccordionContent className="space-y-3"><ProbeEditor label="存活检查 Liveness" value={value.livenessProbe} onChange={(livenessProbe)=>onChange({...value,livenessProbe})}/><ProbeEditor label="就绪检查 Readiness" value={value.readinessProbe} onChange={(readinessProbe)=>onChange({...value,readinessProbe})}/><ProbeEditor label="启动检查 Startup" value={value.startupProbe} onChange={(startupProbe)=>onChange({...value,startupProbe})}/></AccordionContent></AccordionItem>}
      {!isInit && <AccordionItem value="lifecycle"><AccordionTrigger className="text-sm"><span>生命周期<OptionalBadge /></span></AccordionTrigger><AccordionContent className="grid grid-cols-2 gap-4"><LifecycleEditor label="启动后动作 postStart" value={value.postStart} onChange={(postStart)=>onChange({...value,postStart})}/><LifecycleEditor label="停止前动作 preStop" value={value.preStop} onChange={(preStop)=>onChange({...value,preStop})}/></AccordionContent></AccordionItem>}
      {isInit && <div className="py-3 text-xs text-[var(--color-text-tertiary)]">Kubernetes 不允许 InitContainer 配置健康探针和生命周期钩子，因此这里不展示这两类字段。</div>}
      <AccordionItem value="security"><AccordionTrigger className="text-sm"><span>安全与运行设置<OptionalBadge /></span></AccordionTrigger><AccordionContent className="space-y-3"><div className="grid grid-cols-2 gap-3"><Input className="h-8 text-xs" value={value.runAsUser} placeholder="运行用户 UID" onChange={(e)=>onChange({...value,runAsUser:e.target.value})}/><Input className="h-8 text-xs" value={value.runAsGroup} placeholder="运行用户组 GID" onChange={(e)=>onChange({...value,runAsGroup:e.target.value})}/><Input className="h-8 text-xs" value={value.workingDir} placeholder="工作目录 workingDir" onChange={(e)=>onChange({...value,workingDir:e.target.value})}/></div><div className="flex flex-wrap gap-4">{([['allowPrivilegeEscalation','允许权限提升'],['readOnlyRootFilesystem','只读根文件系统'],['runAsNonRoot','必须非 root'],['stdin','保持标准输入'],['tty','分配 TTY']] as const).map(([key,label])=><label key={key} className="flex items-center gap-2 text-xs"><input type="checkbox" checked={value[key]} onChange={(e)=>onChange({...value,[key]:e.target.checked})}/>{label}</label>)}</div><div className="grid grid-cols-2 gap-4"><StringList label="增加 Linux Capabilities" values={value.capabilitiesAdd} onChange={(capabilitiesAdd)=>onChange({...value,capabilitiesAdd})} placeholder="如 NET_ADMIN"/><StringList label="移除 Linux Capabilities" values={value.capabilitiesDrop} onChange={(capabilitiesDrop)=>onChange({...value,capabilitiesDrop})} placeholder="如 ALL"/></div></AccordionContent></AccordionItem>
    </Accordion>
  </div>;
}
